export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  CSRF_FAILED: 'CSRF_FAILED',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  ROOM_BANNED: 'ROOM_BANNED',
  DM_NOT_ALLOWED: 'DM_NOT_ALLOWED',
  INVITATION_INVALID: 'INVITATION_INVALID',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  MESSAGE_GAP_DETECTED: 'MESSAGE_GAP_DETECTED',
} as const;
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
