export const MESSAGE_MAX_BYTES = 3 * 1024;
export const ATTACHMENT_MAX_FILE_BYTES = 20 * 1024 * 1024;
export const ATTACHMENT_MAX_IMAGE_BYTES = 3 * 1024 * 1024;

export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 30;
export const PASSWORD_MIN_LENGTH = 12;
export const PASSWORD_MAX_LENGTH = 128;
export const EMAIL_MAX_LENGTH = 254;
export const ROOM_NAME_MIN_LENGTH = 2;
export const ROOM_NAME_MAX_LENGTH = 50;

export const PAGINATION_DEFAULT_LIMIT = 50;
export const PAGINATION_MAX_LIMIT = 100;
export const PAGINATION_CURSOR_DEFAULT_LIMIT = 25;
export const PAGINATION_CURSOR_MAX_LIMIT = 100;

export const SESSION_TTL_SECONDS_DEFAULT = 30 * 24 * 60 * 60;
export const WEBSOCKET_HEARTBEAT_INTERVAL_MS_DEFAULT = 15_000;
export const WEBSOCKET_STALE_TIMEOUT_MS_DEFAULT = 45_000;
export const WEBSOCKET_AFK_THRESHOLD_MS_DEFAULT = 60_000;
